name: Validar nombre de rama2

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  validar-nombre:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar nombre de la rama
        run: echo "Rama actual: ${{ github.ref_name }}"

      - name: Validar convención de nombre
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Nombre de rama detectado: $BRANCH"
          if echo "$BRANCH" | grep -Eq "^(feature|bugfix|hotfix)/.+$"; then
            echo "✅ Nombre de rama válido."
          else
            echo "::error::❌ Error: El nombre de la rama no cumple con la convención requerida."
            exit 1
